@startuml
class Constants
Constants : float PPM
Constants : float MPP
Constants : int WORLD_PIXEL_WIDTH
Constants : int WORLD_PIXEL_HEIGHT
Constants : int WORLD_WIDTH
Constants : int WORLD_HEIGHT

class CustomTimer
CustomTimer : float totalTime
CustomTimer : float currentTime
CustomTimer : boolean paused
CustomTimer : boolean finished

CustomTimer : elapseTime()
CustomTimer : getFormattedTime()
CustomTimer : pause()
CustomTimer : start()
CustomTimer : stop()
CustomTimer : reset()

class Key
Key : Rectangle Hitbox
Key : Vector2 position
Key : float width
Key : float height

'Used to hold array of where all doors are and creates them out of LockedDoorNodes'
class LockedDoor
LockedDoor : ArrayList doorNodes
LockedDoor : Vector2 position
LockedDoor : String orientation
LockedDoor : int length

LockedDoor : initialiseDoor()


'Used to make up door'
class LockedDoorNode
LockedDoorNode : Rectangle Hitbox
LockedDoorNode : Texture doorTexture
LockedDoorNode : Vector2 position

class Main
Main : create()
Main : resize()
Main : render()
Main : collision()

class Player
Player : float speed
Player : String direction
Player : boolean moving
Player : ArrayList powerupTimers
Player : ArrayList : animations

Player : playerMovement()
Player : addPowerUp()
Player : updateTimers()

Abstract PowerUp
PowerUp : Texture powerUpTexture
PowerUp : String name
PowerUp : String description
PowerUp : String type
PowerUp : float duration

class PowerUpTimer
PowerUpTimer : String name
PowerUpTimer : description
PowerUpTimer : animation idle

'power up is done by name in player addPowerUp method'
class SpeedUp

class Hole

class Charge


class WarpPanel
WarpPanel : Texture texture
WarpPanel : Vector2 position
WarpPanel : boolean visible

WarpPanel : setVisibility()

PowerUp <-- SpeedUp
PowerUp <-- Hole
PowerUp <-- Charge
CustomTimer <-- PowerUpTimer
@enduml